In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import plot_roc_curve
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [2]:
df_b = pd.read_csv("C:/Users/Luyao Li/Desktop/Nlp_Project/Business-Page1 V2.csv")
df_b.head()

E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,web-scraper-order,web-scraper-start-url,book_link,book_link-href,review_link,review_link-href,review_content,book_name,Author,review_count,overall_rating,price,publisher,review date,review rating,language,ISBN,pages
0,1589170375-259609,https://www.amazon.com/s?i=stripbooks&bbn=1000...,The Compound Effect,https://www.amazon.com/Compound-Effect-Darren-...,See all reviews from the United States,https://www.amazon.com/Compound-Effect-Darren-...,A lot of folks who have rated low seem to want...,The Compound Effect,Darren Hardy,"3,332 ratings",4.8 out of 5,$12.39,Publisher: Vanguard Press; Csm edition (Octobe...,"Reviewed in the United States on December 2, 2015",5.0 out of 5 stars,Language: English,ISBN-10: 159315724X,NaN
1,1589168597-229894,https://www.amazon.com/s?i=stripbooks&bbn=1000...,12 Rules for Life: An Antidote to Chaos,https://www.amazon.com/12-Rules-Life-Antidote-...,See all reviews from the United States,https://www.amazon.com/12-Rules-Life-Antidote-...,Very good,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,"12,058 ratings",4.6 out of 5,$14.99,"Publisher: Penguin (May 2, 2019)","Reviewed in the United States on September 4, ...",5.0 out of 5 stars,Language: English,ISBN-10: 0141988517,NaN
2,1589172622-296551,https://www.amazon.com/s?i=stripbooks&bbn=1000...,Mindset: The New Psychology of Success,https://www.amazon.com/Mindset-Psychology-Caro...,See all reviews from the United States,https://www.amazon.com/Mindset-Psychology-Caro...,Seen people recommend Dwecks fixed/growth mind...,Mindset: The New Psychology of Success,Carol S. Dweck,"3,595 ratings",4.5 out of 5,$10.15,"Publisher: Ballantine Books; Reprint, Updated ...","Reviewed in the United States on August 20, 2015",1.0 out of 5 stars,Language: English,ISBN-10: 0345472322,NaN
3,1589172622-297296,https://www.amazon.com/s?i=stripbooks&bbn=1000...,Mindset: The New Psychology of Success,https://www.amazon.com/Mindset-Psychology-Caro...,See all reviews from the United States,https://www.amazon.com/Mindset-Psychology-Caro...,This is a must read for anyone interested in t...,Mindset: The New Psychology of Success,Carol S. Dweck,"3,595 ratings",4.5 out of 5,$10.15,"Publisher: Ballantine Books; Reprint, Updated ...","Reviewed in the United States on December 23, ...",5.0 out of 5 stars,Language: English,ISBN-10: 0345472322,NaN
4,1589172622-295614,https://www.amazon.com/s?i=stripbooks&bbn=1000...,Mindset: The New Psychology of Success,https://www.amazon.com/Mindset-Psychology-Caro...,See all reviews from the United States,https://www.amazon.com/Mindset-Psychology-Caro...,Repetitive. Book could have been cut in half....,Mindset: The New Psychology of Success,Carol S. Dweck,"3,595 ratings",4.5 out of 5,$10.15,"Publisher: Ballantine Books; Reprint, Updated ...","Reviewed in the United States on July 12, 2019",2.0 out of 5 stars,Language: English,ISBN-10: 0345472322,NaN

In [3]:
df_c = pd.read_csv("C:/Users/Luyao Li/Desktop/Nlp_Project/Children-Page1 V2.csv")
df_c.head()

E:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,web-scraper-order,web-scraper-start-url,book_link,book_link-href,review_link,review_link-href,review_content,book_name,Author,review_count,overall_rating,price,publisher,review date,review rating,language,ISBN,pages
0,1589152052-79960,https://www.amazon.com/s?i=stripbooks&bbn=1000...,Kindergarten writing paper with lines for ABC ...,https://www.amazon.com/Kindergarten-writing-pa...,See all reviews from the United States,https://www.amazon.com/Kindergarten-writing-pa...,Awesome writing paper for my kindergartener. W...,Kindergarten writing paper with lines for ABC ...,NaN,434 ratings,4.9 out of 5,$5.99,"Publisher: Independently published (May 10, 2019)","Reviewed in the United States on February 10, ...",5.0 out of 5 stars,Language: English,ISBN-13: 978-1097704675,Paperback: 120 pages
1,1589147170-3430,https://www.amazon.com/s?i=stripbooks&bbn=1000...,School Zone - Get Ready for Kindergarten Workb...,https://www.amazon.com/Get-Ready-Kindergarten-...,See all reviews from the United States,https://www.amazon.com/Get-Ready-Kindergarten-...,Got this for my granddaughters PreK graduation...,School Zone - Get Ready for Kindergarten Workb...,NaN,208 ratings,4.8 out of 5,$9.89,"Publisher: School Zone Publishing (May 14, 2017)","Reviewed in the United States on June 19, 2019",5.0 out of 5 stars,Language: English,ISBN-13: 978-0887436802,Paperback: 256 pages
2,1589153837-108811,https://www.amazon.com/s?i=stripbooks&bbn=1000...,"I Am Confident, Brave & Beautiful: A Coloring ...",https://www.amazon.com/Am-Confident-Brave-Beau...,See all reviews from the United States,https://www.amazon.com/Am-Confident-Brave-Beau...,The book came with a giant spot where it had g...,"I Am Confident, Brave & Beautiful: A Coloring ...",Hopscotch Girls,"4,170 ratings",4.8 out of 5,$8.33,Publisher: Hopscotch Girls; 32st edition (Nove...,"Reviewed in the United States on December 10, ...",1.0 out of 5 stars,Language: English,ISBN-13: 978-0692927991,Paperback: 24 pages
3,1589147924-14497,https://www.amazon.com/s?i=stripbooks&bbn=1000...,The Outdoor Toddler Activity Book: 100+ Fun Ea...,https://www.amazon.com/Outdoor-Toddler-Activit...,See all reviews from the United States,https://www.amazon.com/Outdoor-Toddler-Activit...,This book has been such a great asset to our f...,The Outdoor Toddler Activity Book: 100+ Fun Ea...,Krissy Bonning-Gould,96 ratings,4.7 out of 5,$9.97,"Publisher: Rockridge Press (April 2, 2019)","Reviewed in the United States on May 16, 2019",5.0 out of 5 stars,Language: English,ISBN-13: 978-1641523516,Paperback: 176 pages
4,1589153733-107789,https://www.amazon.com/s?i=stripbooks&bbn=1000...,Preschool Math Workbook for Toddlers Ages 2-4:...,https://www.amazon.com/Preschool-Math-Workbook...,See all reviews from the United States,https://www.amazon.com/Preschool-Math-Workbook...,My 3 year old loves this book for his homescho...,Preschool Math Workbook for Toddlers Ages 2-4:...,Modern Kid Press,526 ratings,4.6 out of 5,$6.99,"Publisher: Modern Kid Press (October 29, 2019)","Reviewed in the United States on March 22, 2020",5.0 out of 5 stars,Language: English,ISBN-13: 978-1948209885,Paperback: 83 pages

In [4]:
df_h = pd.read_csv("C:/Users/Luyao Li/Desktop/Nlp_Project/Humor-Page1 V2.csv")
df_h.head()

,web-scraper-order,web-scraper-start-url,book_link,book_link-href,review_link,review_link-href,review_content,book_name,Author,review_count,overall_rating,price,publisher,review date,review rating,language,ISBN,pages
0,1589623513-146176,https://www.amazon.com/s?i=stripbooks&bbn=1000...,The Beauty of Horror 1: A GOREgeous Coloring Book,https://www.amazon.com/Beauty-Horror-GOREgeous...,See all reviews from the United States,https://www.amazon.com/Beauty-Horror-GOREgeous...,It's filled with just the right amount of beau...,The Beauty of Horror 1: A GOREgeous Coloring Book,Alan Robert,"1,390 ratings",4.8 out of 5,$15.98,Publisher: IDW Publishing; Clr Csm edition (Oc...,"Reviewed in the United States on April 24, 2018",5.0 out of 5 stars,Language: English,ISBN-13: 978-1631407284,Paperback: 80 pages
1,1589622716-132029,https://www.amazon.com/s?i=stripbooks&bbn=1000...,Slaughterhouse-Five: A Novel (Modern Library 1...,https://www.amazon.com/Slaughterhouse-Five-Nov...,See all reviews from the United States,https://www.amazon.com/Slaughterhouse-Five-Nov...,There is no doubt in my mind that Kurt Vonnegu...,Slaughterhouse-Five: A Novel (Modern Library 1...,Kurt Vonnegut,"3,473 ratings",4.3 out of 5,$7.79,Publisher: Dial Press Trade Paperback; Reissue...,"Reviewed in the United States on August 25, 2017",5.0 out of 5 stars,Language: English,ISBN-13: 978-0812988529,Paperback: 288 pages
2,1589624780-165498,https://www.amazon.com/s?i=stripbooks&bbn=1000...,Wacky Waving Inflatable Tube Guy (RP Minis),https://www.amazon.com/Wacky-Waving-Inflatable...,See all reviews from the United States,https://www.amazon.com/Wacky-Waving-Inflatable...,Should have listened to the other reviews. I h...,Wacky Waving Inflatable Tube Guy (RP Minis),NaN,"4,319 ratings",4 out of 5,$7.99,"Publisher: RP Minis (October 2, 2018)","Reviewed in the United States on February 1, 2019",2.0 out of 5 stars,Language: English,ISBN-13: 978-0762462872,Paperback: 32 pages
3,1589622716-132077,https://www.amazon.com/s?i=stripbooks&bbn=1000...,Slaughterhouse-Five: A Novel (Modern Library 1...,https://www.amazon.com/Slaughterhouse-Five-Nov...,See all reviews from the United States,https://www.amazon.com/Slaughterhouse-Five-Nov...,"Stumbling around for something good to read, I...",Slaughterhouse-Five: A Novel (Modern Library 1...,Kurt Vonnegut,"3,473 ratings",4.3 out of 5,$7.79,Publisher: Dial Press Trade Paperback; Reissue...,"Reviewed in the United States on September 3, ...",5.0 out of 5 stars,Language: English,ISBN-13: 978-0812988529,Paperback: 288 pages
4,1589623266-143135,https://www.amazon.com/s?i=stripbooks&bbn=1000...,The Screaming Goat (Book & Figure),https://www.amazon.com/The-Screaming-Goat-Book...,See all reviews from the United States,https://www.amazon.com/The-Screaming-Goat-Book...,It was smaller then I expected but was absolut...,The Screaming Goat (Book & Figure),NaN,"3,149 ratings",4.5 out of 5,$9.95,"Publisher: RP Minis; Pap/Toy edition (April 5,...","Reviewed in the United States on January 9, 2020",5.0 out of 5 stars,Language: English,ISBN-13: 978-0762459810,Paperback: 32 pages

In [5]:
df_b=df_b.drop(['web-scraper-order', 'web-scraper-start-url', 'book_link',
       'book_link-href', 'review_link', 'review_link-href','Author', 'review_count', 'overall_rating', 'price',
       'publisher', 'review date','pages', 'book_name','language', 'ISBN'],axis=1)

In [6]:
df_b.head()

                                      review_content       review rating
0  A lot of folks who have rated low seem to want...  5.0 out of 5 stars
1                                          Very good  5.0 out of 5 stars
2  Seen people recommend Dwecks fixed/growth mind...  1.0 out of 5 stars
3  This is a must read for anyone interested in t...  5.0 out of 5 stars
4  Repetitive.  Book could have been cut in half....  2.0 out of 5 stars

In [7]:
df_b["review rating"] = df_b["review rating"].astype(str).str.extract("(\d)", expand = True)
df_b.head()

                                      review_content review rating
0  A lot of folks who have rated low seem to want...             5
1                                          Very good             5
2  Seen people recommend Dwecks fixed/growth mind...             1
3  This is a must read for anyone interested in t...             5
4  Repetitive.  Book could have been cut in half....             2

In [8]:
df_b["Category"] = "Business"
df_b.head()

                                      review_content review rating  Category
0  A lot of folks who have rated low seem to want...             5  Business
1                                          Very good             5  Business
2  Seen people recommend Dwecks fixed/growth mind...             1  Business
3  This is a must read for anyone interested in t...             5  Business
4  Repetitive.  Book could have been cut in half....             2  Business

In [9]:
df_c=df_c.drop(['web-scraper-order', 'web-scraper-start-url', 'book_link',
       'book_link-href', 'review_link', 'review_link-href','Author', 'review_count', 'overall_rating', 'price',
       'publisher', 'review date','pages', 'book_name','language', 'ISBN'],axis=1)

In [10]:
df_c.head()

                                      review_content       review rating
0  Awesome writing paper for my kindergartener. W...  5.0 out of 5 stars
1  Got this for my granddaughters PreK graduation...  5.0 out of 5 stars
2  The book came with a giant spot where it had g...  1.0 out of 5 stars
3  This book has been such a great asset to our f...  5.0 out of 5 stars
4  My 3 year old loves this book for his homescho...  5.0 out of 5 stars

In [11]:
df_c["review rating"] = df_c["review rating"].astype(str).str.extract("(\d)", expand = True)
df_c.head()

                                      review_content review rating
0  Awesome writing paper for my kindergartener. W...             5
1  Got this for my granddaughters PreK graduation...             5
2  The book came with a giant spot where it had g...             1
3  This book has been such a great asset to our f...             5
4  My 3 year old loves this book for his homescho...             5

In [12]:
df_c["Category"] = "Children"
df_b.head()

                                      review_content review rating  Category
0  A lot of folks who have rated low seem to want...             5  Business
1                                          Very good             5  Business
2  Seen people recommend Dwecks fixed/growth mind...             1  Business
3  This is a must read for anyone interested in t...             5  Business
4  Repetitive.  Book could have been cut in half....             2  Business

In [13]:
df_h=df_h.drop(['web-scraper-order', 'web-scraper-start-url', 'book_link',
       'book_link-href', 'review_link', 'review_link-href','Author', 'review_count', 'overall_rating', 'price',
       'publisher', 'review date','pages', 'book_name','language', 'ISBN'],axis=1)

In [14]:
df_h.head()

                                      review_content       review rating
0  It's filled with just the right amount of beau...  5.0 out of 5 stars
1  There is no doubt in my mind that Kurt Vonnegu...  5.0 out of 5 stars
2  Should have listened to the other reviews. I h...  2.0 out of 5 stars
3  Stumbling around for something good to read, I...  5.0 out of 5 stars
4  It was smaller then I expected but was absolut...  5.0 out of 5 stars

In [15]:
df_h["review rating"] = df_h["review rating"].astype(str).str.extract("(\d)", expand = True)
df_h.head()

                                      review_content review rating
0  It's filled with just the right amount of beau...             5
1  There is no doubt in my mind that Kurt Vonnegu...             5
2  Should have listened to the other reviews. I h...             2
3  Stumbling around for something good to read, I...             5
4  It was smaller then I expected but was absolut...             5

In [16]:
df_h["Category"] = "Humor"
df_h.head()

                                      review_content review rating Category
0  It's filled with just the right amount of beau...             5    Humor
1  There is no doubt in my mind that Kurt Vonnegu...             5    Humor
2  Should have listened to the other reviews. I h...             2    Humor
3  Stumbling around for something good to read, I...             5    Humor
4  It was smaller then I expected but was absolut...             5    Humor

In [17]:
df = pd.concat([df_b,df_c,df_h],ignore_index=True )
df.head()

                                      review_content review rating  Category
0  A lot of folks who have rated low seem to want...             5  Business
1                                          Very good             5  Business
2  Seen people recommend Dwecks fixed/growth mind...             1  Business
3  This is a must read for anyone interested in t...             5  Business
4  Repetitive.  Book could have been cut in half....             2  Business

In [18]:
df['review rating'] =df['review rating'].astype(float)

In [19]:
df = df[df['review rating'] != 3]

In [20]:
df.loc[df['review rating'] > 3, 'Label'] = 1
df.loc[df['review rating'] < 3, 'Label'] = 0

In [21]:
df['review_content'] =df['review_content'].astype(str)

In [22]:
df['Label'] =df['Label'].astype(int)
df.head()

,review_content,review rating,Category,Label
0,A lot of folks who have rated low seem to want...,5.0,Business,1
1,Very good,5.0,Business,1
2,Seen people recommend Dwecks fixed/growth mind...,1.0,Business,0
3,This is a must read for anyone interested in t...,5.0,Business,1
4,Repetitive. Book could have been cut in half....,2.0,Business,0

In [23]:
df_class0 = df[df["Label"] == 0]
df_class1 = df[df["Label"] == 1]

In [24]:
df_class1_sample = df_class1.sample(n = df_class0.shape[0], random_state = 203)

In [25]:
df_new = pd.concat([df_class0, df_class1_sample], axis = 0, ignore_index = True)

In [26]:
df_new.head()

,review_content,review rating,Category,Label
0,Seen people recommend Dwecks fixed/growth mind...,1.0,Business,0
1,Repetitive. Book could have been cut in half....,2.0,Business,0
2,During the Gold Rush there were two ways to ge...,2.0,Business,0
3,Most of the content in this book is pretty obv...,2.0,Business,0
4,This must have been my most disappointing buy ...,1.0,Business,0

# Dataset For Sentiment Analysis

In [27]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [28]:
X = df_new["review_content"]
y = df_new["Label"]

In [29]:
X.head()

0    Seen people recommend Dwecks fixed/growth mind...
1    Repetitive.  Book could have been cut in half....
2    During the Gold Rush there were two ways to ge...
3    Most of the content in this book is pretty obv...
4    This must have been my most disappointing buy ...
Name: review_content, dtype: object

# TF-IDF

In [30]:
tfidf = TfidfVectorizer(min_df = 5, ngram_range= (1,1), max_df = 0.9)
X_tfidf= tfidf.fit_transform(X)

In [31]:
X_tfidf.shape

(34864, 13228)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size = 0.3, random_state = 203)

In [33]:
X_train.shape

(24404, 13228)

# XGBoost

In [34]:
xgb = XGBClassifier(learning_rate=0.02, n_estimators=600,
                    objective='binary:logistic', random_state=203)

In [35]:
xgb.fit(X_train, y_train)
pred_xgb = xgb.predict(X_test)

In [36]:
roc_auc_score(pred_xgb, y_test)

0.8414044723857028

In [37]:
accuracy_score(pred_xgb, y_test)

0.8414913957934991

In [38]:
confusion_matrix(pred_xgb, y_test)

array([[4310,  856],
       [ 802, 4492]], dtype=int64)

In [39]:
plot_roc_curve(xgb, X_test, y_test)

In [40]:
from ipywidgets import widgets
from IPython.display import display

In [41]:
print("Please input reviews:")
inputText = widgets.Text()
display(inputText)

button = widgets.Button(description = "SUBMIT")
display(button)

def on_button_clicked(b):
    X_new = X
    str = pd.Series(inputText.value)
    X_new = X_new.append(str)
    tfidf_new = TfidfVectorizer(min_df = 5, ngram_range= (1,1), max_df = 0.9, max_features = 13228)
    X_new_transformed= tfidf_new.fit_transform(X_new)
    #X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new_transformed, y, test_size = 0.3, random_state = 203)
    X_train_new = X_new_transformed[:-10461]
    X_test_new = X_new_transformed[-10461:]
    y_train_new = y[:-10460]
    y_test_new = y[-10460:]
    print("Analyzing, please wait......")
    xgb = XGBClassifier(learning_rate=0.02, n_estimators=600,
                        objective='binary:logistic', random_state=203)
    xgb.fit(X_train_new, y_train_new)
    test_new = X_test_new[-1]
    pred = xgb.predict(test_new)
    if pred[0] == 0:
        pred_text = "Negative"
    else:
        pred_text = "Positive"
    print("Sentiment:   ", pred_text)
    
button.on_click(on_button_clicked)

Please input reviews:

Text(value='')

Button(description='SUBMIT', style=ButtonStyle())